<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PEye.CLI</RootNamespace>
    <AssemblyName>PEye</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>1.0.0</Version>
    <Authors>Ehabal7ab</Authors>
    <Company>PEye</Company>
    <Product>PEye</Product>
    <Description>Windows-based Static Malware Analysis Tool</Description>
    <Copyright>Copyright © 2025</Copyright>
    <PackageProjectUrl>https://github.com/Ehabal7ab/PEye</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Ehabal7ab/PEye</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>malware;analysis;security;pe;static-analysis</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Core\*.cs" Link="Core\%(Filename)%(Extension)" />
    <Compile Include="..\Utils\*.cs" Link="Utils\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>